name: 596-15_analyses
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc
  - trimmomatic
  - unicycler
  - sourmash
  - fastani
  - numpy
  - pip
  - pip:
    - assemblyStatistics


