#!/bin/bash

mkdir unicycler_output
mkdir raw_fastqs/trimmed_paired
mkdir singleM_output
mkdir singleM_DB
curl -L https://zenodo.org/records/8419620/files/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb.tar.gz?download=1 -o singleM_DB/S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb.tar.gz
cd singleM_DB
tar -xvzf S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb.tar.gz
rm S3.2.1.GTDB_r214.metapackage_20231006.smpkg.zb.tar.gz
cd ..
